### ISSUE TITLE
Doesn't work in R 4.0.3

### ISSUE THREAD

**Issue by albert-ying** [paulklemm/rvisidata#9] opened 2021-04-24 01:24 UTC
Hi, I just found visidata and this amazing package when I was frustrated with excel. Visidata itself works well to me, but I tried the example of this package, it doesn't work somehow.

## Steps
1. Open R with `R --vanilla`, everything in my .visdatarc are commented out.
2. `rvisidata::vd(iris)`

It gives
<img width="726" alt="image" src="https://user-images.githubusercontent.com/59846322/115942859-4a08fb00-a47a-11eb-9a3c-6771c059f0ce.png">

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.0.3  jsonlite_1.7.2  rvisidata_0.0.3
```

**Comment by torbjorn-sjoberg-voi** [comment] 2021-04-24 23:20
I have the exact same issue! :/

**Comment by torbjorn-sjoberg-voi** [comment] 2021-04-25 00:00
I did some quick testing and there seems to be something off with the json part of the code!

Removing line 9-13 in main.r made the code for me.

![image](https://user-images.githubusercontent.com/74357349/115976028-0c839b00-a56a-11eb-9832-2ddb7892bc84.png)

**Comment by paulklemm** [comment] 2021-04-26 07:35
I can't reproduce. I pushed a potential fix, can you please verify if you still have this error?

**Comment by torbjorn-sjoberg-voi** [comment] 2021-04-26 07:45
Sadly, did not work. 
![image](https://user-images.githubusercontent.com/74357349/116047157-142f6680-a674-11eb-8914-025c4f7a1c78.png)

It is very strange howver foxusing on a row displays the values correctly!
![image](https://user-images.githubusercontent.com/74357349/116047248-2d381780-a674-11eb-9cd5-2064f98edad0.png)

**Comment by albert-ying** [comment] 2021-04-26 07:56
Same here, seems like some weird thing happens to the numeric columns. Also when I try to edit the cells, the character column works fine, but for the numeric columns, it gives me an error `TypeError: 「NoneType' object does not support item assignment|
`

**Comment by torbjorn-sjoberg-voi** [comment] 2021-04-26 09:55
macOS here aswell

**Comment by matthewstrasiotto** [comment] 2021-06-17 05:20
Hm, looks like the json serializer is wrapping scalars weirdly or something.

@albert-ying rvisidata doesn't support editing the data in any meaningful way, so I advise you against that, but what you're describing is still a bug

**Comment by matthewstrasiotto** [comment] 2021-06-17 05:23
@torbjorn-sjoberg-voi hi - can you provide a `sessionInfo` like @albert-ying ?

**Comment by matthewstrasiotto** [comment] 2021-06-17 05:38
I can't reproduce this on R 3.6.*  rn

**Comment by paulklemm** [comment] 2024-05-02 13:47
Is this issue still relevant? Will otherwise close it.

**Closed** 2024-05-06 07:53 UTC
